apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: similar-materials-pipeline # executable id, must be unique across all your workflows (YAML files)
  annotations:
    scenarios.ai.sap.com/description: "Similar Materials Attributes"
    scenarios.ai.sap.com/name: "Similar Materials Attributes" # Scenario name should be the use case
    executables.ai.sap.com/description: "Create online server to make live predictions"
    executables.ai.sap.com/name: "server"
    artifacts.ai.sap.com/similarAttributes.kind: "dataset" # Helps in suggesting the kind of artifact that can be attached.
  labels:
    scenarios.ai.sap.com/id: "similar-materials-attributes"
    ai.sap.com/version: "1.0"
spec:
  inputs:
    artifacts:
      - name: similarAttributes # placeholder name, do not add `-` in value use only alphanumeric chars
        path: /app/data/ # where to copy in the Dataset in the Docker image
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency   # condition when to scale
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter # computing power
    spec: |
      predictor:
        imagePullSecrets:
          - name: rohanreddy-docker-registry  # your docker registry secret
        minReplicas: 1
        maxReplicas: 5    # how much to scale
        containers:
        - name: kserve-container
          image: "docker.io/rohandoc99/similar-material-server:01"
          ports:
            - containerPort: 9001    # customizable port
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "Starting" && gunicorn --chdir /app/src main:app --timeout 10000 -b 0.0.0.0:9001 # filename `main` flask variable `app`
          env:
            - name: STORAGE_URI # Required
              value: "{{inputs.artifacts.similarAttributes}}" # Required reference from artifact name, see above
